# Generated by Django 4.2.11 on 2024-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
